version: "3.7"

services:
  make_my_change_docs:
    image: node:18-alpine
    container_name: make_my_change_docs
    working_dir: "/app"
    user: 1000:1000
    volumes:
      - .:/app
    ports:
      - 3000:3000
